import type { ArticleBlockDef } from "@/lib/article";

/**
 * Block order/kind for `content/i18n/en|ur/about.ts`'s
 * `ourStory.blocks`/`missionVision.missionBlocks`/`missionVision.visionBlocks`
 * — restructured from the ARTICLES source document's "Our Story" and
 * "Mission & Vision" articles (lib/article.ts). Structural fact, not
 * translatable copy — mirrors lib/seminary.ts's own structure/content
 * split.
 */
/** Slugs of the full leadership biographies (lib/resources.ts's `leadershipResources`), linked from the About page's leadership cards via "Read more". */
export const leadershipSlugs = {
  nayyer: "pastor-nayyer-gull",
  rahmat: "pastor-rahmat-masih",
} as const;

export const ourStoryBlocks: ArticleBlockDef[] = [
  { key: "dek", kind: "subheading" },
  { key: "leadP1", kind: "paragraph" },
  { key: "beginningHeading", kind: "heading" },
  { key: "beginningP1", kind: "paragraph" },
  { key: "beginningP2", kind: "paragraph" },
  { key: "beginningP3", kind: "paragraph" },
  { key: "beginningP4", kind: "paragraph" },
  { key: "beginningP5", kind: "paragraph" },
  { key: "beginningP6", kind: "paragraph" },
  { key: "chapterHeading", kind: "heading" },
  { key: "chapterP1", kind: "paragraph" },
  { key: "chapterP2", kind: "paragraph" },
  { key: "chapterP3", kind: "paragraph" },
  { key: "chapterP4", kind: "paragraph" },
  { key: "chapterP5", kind: "paragraph" },
  { key: "chapterP6", kind: "paragraph" },
  { key: "chapterP7", kind: "paragraph" },
  { key: "chapterP8", kind: "paragraph" },
  { key: "notAloneHeading", kind: "heading" },
  { key: "notAloneP1", kind: "paragraph" },
  { key: "notAloneP2", kind: "paragraph" },
  { key: "notAloneP3", kind: "paragraph" },
  { key: "notAloneP4", kind: "paragraph" },
  { key: "notAloneP5", kind: "paragraph" },
  { key: "notAloneP6", kind: "paragraph" },
  { key: "notAloneP7", kind: "paragraph" },
  { key: "notAloneP8", kind: "paragraph" },
  { key: "notAloneP9", kind: "paragraph" },
  { key: "notAloneP10", kind: "paragraph" },
  { key: "notAloneP11", kind: "paragraph" },
  { key: "notAloneP12", kind: "paragraph" },
  { key: "legacyHeading", kind: "heading" },
  { key: "legacyP1", kind: "paragraph" },
  { key: "legacyP2", kind: "paragraph" },
  { key: "legacyP3", kind: "paragraph" },
  { key: "legacyP4", kind: "paragraph" },
  { key: "legacyP5", kind: "paragraph" },
  { key: "legacyP6", kind: "paragraph" },
  { key: "journeyHeading", kind: "heading" },
  { key: "journeyP1", kind: "paragraph" },
  { key: "journeyP2", kind: "paragraph" },
  { key: "journeyP3", kind: "paragraph" },
  { key: "journeyP4", kind: "paragraph" },
  { key: "journeyP5", kind: "paragraph" },
  { key: "journeyP6", kind: "paragraph" },
];

export const missionBlocks: ArticleBlockDef[] = [
  { key: "whyHeading", kind: "heading" },
  { key: "whyP1", kind: "paragraph" },
  { key: "whyP2", kind: "paragraph" },
  { key: "whyP3", kind: "paragraph" },
  { key: "missionHeading", kind: "heading" },
  { key: "missionP1", kind: "paragraph" },
  { key: "proclaimingSub", kind: "subheading" },
  { key: "proclaimingP1", kind: "paragraph" },
  { key: "proclaimingP2", kind: "paragraph" },
  { key: "strengtheningSub", kind: "subheading" },
  { key: "strengtheningP1", kind: "paragraph" },
  { key: "strengtheningP2", kind: "paragraph" },
  { key: "strengtheningP3", kind: "paragraph" },
  { key: "trainingSub", kind: "subheading" },
  { key: "trainingP1", kind: "paragraph" },
  { key: "trainingP2", kind: "paragraph" },
  { key: "literatureSub", kind: "subheading" },
  { key: "literatureP1", kind: "paragraph" },
  { key: "literatureP2", kind: "paragraph" },
  { key: "literatureP3", kind: "paragraph" },
  { key: "musicSub", kind: "subheading" },
  { key: "musicP1", kind: "paragraph" },
  { key: "musicP2", kind: "paragraph" },
  { key: "musicP3", kind: "paragraph" },
  { key: "childrenSub", kind: "subheading" },
  { key: "childrenP1", kind: "paragraph" },
  { key: "childrenP2", kind: "paragraph" },
  { key: "childrenP3", kind: "paragraph" },
  { key: "childrenP4", kind: "paragraph" },
  { key: "childrenP5", kind: "paragraph" },
];

export const visionBlocks: ArticleBlockDef[] = [
  { key: "visionHeading", kind: "heading" },
  { key: "visionDek", kind: "subheading" },
  { key: "visionP1", kind: "paragraph" },
  { key: "visionP2", kind: "paragraph" },
  { key: "visionP3", kind: "paragraph" },
  { key: "everyChildSub", kind: "subheading" },
  { key: "everyChildP1", kind: "paragraph" },
  { key: "everyChildP2", kind: "paragraph" },
  { key: "everyChildP3", kind: "paragraph" },
  { key: "empoweringSub", kind: "subheading" },
  { key: "empoweringP1", kind: "paragraph" },
  { key: "empoweringP2", kind: "paragraph" },
  { key: "empoweringP3", kind: "paragraph" },
  { key: "characterSub", kind: "subheading" },
  { key: "characterP1", kind: "paragraph" },
  { key: "characterP2", kind: "paragraph" },
  { key: "characterP3", kind: "paragraph" },
  { key: "betterPakistanSub", kind: "subheading" },
  { key: "betterPakistanP1", kind: "paragraph" },
  { key: "betterPakistanP2", kind: "paragraph" },
  { key: "betterPakistanP3", kind: "paragraph" },
  { key: "betterPakistanP4", kind: "paragraph" },
  { key: "pathOutSub", kind: "subheading" },
  { key: "pathOutP1", kind: "paragraph" },
  { key: "pathOutP2", kind: "paragraph" },
  { key: "pathOutP3", kind: "paragraph" },
  { key: "pathOutP4", kind: "paragraph" },
  { key: "impactHeading", kind: "heading" },
  { key: "impactDek", kind: "subheading" },
  { key: "impactP1", kind: "paragraph" },
  { key: "impactP2", kind: "paragraph" },
  { key: "impactP3", kind: "paragraph" },
  { key: "supportSub", kind: "subheading" },
  { key: "supportIntro", kind: "paragraph" },
  {
    key: "supportList",
    kind: "list",
    itemKeys: ["supportItem1", "supportItem2", "supportItem3", "supportItem4", "supportItem5"],
  },
  { key: "supportP1", kind: "paragraph" },
  { key: "childLaborSub", kind: "subheading" },
  { key: "childLaborP1", kind: "paragraph" },
  { key: "childLaborP2", kind: "paragraph" },
  { key: "childLaborP3", kind: "paragraph" },
  { key: "practicalHelpSub", kind: "subheading" },
  { key: "practicalHelpP1", kind: "paragraph" },
  { key: "practicalHelpP2", kind: "paragraph" },
  { key: "practicalHelpP3", kind: "paragraph" },
  { key: "valuesHeading", kind: "heading" },
  { key: "valuesDek", kind: "subheading" },
  { key: "faithSub", kind: "subheading" },
  { key: "faithP1", kind: "paragraph" },
  { key: "faithP2", kind: "paragraph" },
  { key: "faithP3", kind: "paragraph" },
  { key: "truthSub", kind: "subheading" },
  { key: "truthP1", kind: "paragraph" },
  { key: "truthP2", kind: "paragraph" },
  { key: "prayerSub", kind: "subheading" },
  { key: "prayerP1", kind: "paragraph" },
  { key: "prayerP2", kind: "paragraph" },
  { key: "loveSub", kind: "subheading" },
  { key: "loveP1", kind: "paragraph" },
  { key: "loveP2", kind: "paragraph" },
  { key: "serviceSub", kind: "subheading" },
  { key: "serviceP1", kind: "paragraph" },
  { key: "serviceP2", kind: "paragraph" },
  { key: "integritySub", kind: "subheading" },
  { key: "integrityP1", kind: "paragraph" },
  { key: "integrityP2", kind: "paragraph" },
  { key: "educationSub", kind: "subheading" },
  { key: "educationP1", kind: "paragraph" },
  { key: "educationP2", kind: "paragraph" },
  { key: "helpingSub", kind: "subheading" },
  { key: "helpingP1", kind: "paragraph" },
  { key: "helpingP2", kind: "paragraph" },
  { key: "helpingP3", kind: "paragraph" },
  { key: "commitmentHeading", kind: "heading" },
  { key: "commitmentDek", kind: "subheading" },
  { key: "commitmentP1", kind: "paragraph" },
  { key: "commitmentP2", kind: "paragraph" },
  { key: "commitmentP3", kind: "paragraph" },
];
